export const COMPETITION_CREATE_REQUEST = "COMPETITION_CREATE_REQUEST";
export const COMPETITION_CREATE_SUCCESS = "COMPETITION_CREATE_SUCCESS";
export const COMPETITION_CREATE_ERROR = "COMPETITION_CREATE_ERROR";
export const COMPETITION_NOTIFICATION = "COMPETITION_NOTIFICATION";
export const COMPETITION_FETCH_REQUEST = "COMPETITION_FETCH_REQUEST";
export const COMPETITION_FETCH_SUCCESS = "COMPETITION_FETCH_SUCCESS";
export const COMPETITION_FETCH_ERROR = "COMPETITION_FETCH_ERROR";
export const COMPETITION_UPDATE_REQUEST = "COMPETITION_UPDATE_REQUEST";
export const COMPETITION_UPDATE_SUCCESS = "COMPETITION_UPDATE_SUCCESS";
export const COMPETITION_UPDATE_ERROR = "COMPETITION_UPDATE_ERROR";
export const COMPETITION1_FETCH_REQUEST = "COMPETITION1_FETCH_REQUEST";
export const COMPETITION1_FETCH_SUCCESS = "COMPETITION1_FETCH_SUCCESS";
export const COMPETITION1_FETCH_ERROR = "COMPETITION1_FETCH_ERROR";
export const COMPETITIONS_UPDATE_REQUEST = "COMPETITIONS_UPDATE_REQUEST";
export const COMPETITIONS_UPDATE_SUCCESS = "COMPETITIONS_UPDATE_SUCCESS";
export const COMPETITIONS_UPDATE_ERROR = "COMPETITIONS_UPDATE_ERROR";
export const COMPETITIONS_DELETE_REQUEST = "COMPETITIONS_DELETE_REQUEST";
export const COMPETITIONS_DELETE_SUCCESS = "COMPETITIONS_DELETE_SUCCESS";
export const COMPETITIONS_DELETE_ERROR = "COMPETITIONS_DELETE_ERROR";

export const COMPETITION_STATUS_REQUEST = "COMPETITION_STATUS_REQUEST";
export const COMPETITION_STATUS_SUCCESS = "COMPETITION_STATUS_SUCCESS";
export const COMPETITION_STATUS_ERROR = "COMPETITION_STATUS_ERROR";

export const COMPETITION_RESULT_REQUEST = "COMPETITION_RESULT_REQUEST";
export const COMPETITION_RESULT_SUCCESS = "COMPETITION_RESULT_SUCCESS";
export const COMPETITION_RESULT_ERROR = "COMPETITION_RESULT_ERROR";
