export const QUESTION_FETCH_REQUEST = "QUESTION_FETCH_REQUEST";
export const QUESTION_FETCH_SUCCESS = "QUESTION_FETCH_SUCCESS";
export const QUESTION_FETCH_ERROR = "QUESTION_FETCH_ERROR";

export const QUESTION_LOAD_REQUEST = "QUESTION_LOAD_REQUEST";
export const QUESTION_LOAD_SUCCESS = "QUESTION_LOAD_SUCCESS";
export const QUESTION_LOAD_ERROR = "QUESTION_LOAD_ERROR";

export const QUESTION_NOTIFICATION = "QUESTION_NOTIFICATION";
