export const QUESTION_DIFFICULT_FETCH_REQUEST =
  "QUESTION_DIFFICULT_FETCH_REQUEST";
export const QUESTION_DIFFICULT_FETCH_SUCCESS =
  "QUESTION_DIFFICULT_FETCH_SUCCESS";
export const QUESTION_DIFFICULT_FETCH_ERROR = "QUESTION_DIFFICULT_FETCH_ERROR";
