export const QUESTION_SKILL_FETCH_REQUEST = "QUESTION_SKILL_FETCH_REQUEST";
export const QUESTION_SKILL_FETCH_SUCCESS = "QUESTION_SKILL_FETCH_SUCCESS";
export const QUESTION_SKILL_FETCH_ERROR = "QUESTION_SKILL_FETCH_ERROR";
